name: tots_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  http: ^1.2.2
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.8.0
  hive_test: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - .env

