// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNtmqxEOwTJJ-edpElVQezFTL6FrZZKKQ',
    appId: '1:286797280227:android:aba13c61c4aaa30b36e6d6',
    messagingSenderId: '286797280227',
    projectId: 'airy-cortex-300214',
    databaseURL: 'https://airy-cortex-300214-default-rtdb.firebaseio.com',
    storageBucket: 'airy-cortex-300214.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsUO8IM8rkYeXXRCr-eMeEAJJhVSJYlag',
    appId: '1:286797280227:ios:9cd997448a64df7636e6d6',
    messagingSenderId: '286797280227',
    projectId: 'airy-cortex-300214',
    databaseURL: 'https://airy-cortex-300214-default-rtdb.firebaseio.com',
    storageBucket: 'airy-cortex-300214.appspot.com',
    iosBundleId: 'com.example.totsTest',
  );
}
